### ISSUE TITLE
Don't display decision timer at the end of the movie

### ISSUE THREAD

**Issue by roschaefer** [tino-junge/cinema-app#38]
My config.yml looks like this:
```
remote_url: [...]
video:
  v1:
    file: 'iamerror_01.mp4'
```
At the end of the clip the decision timer fades in. Even if we are at the end of the whole movie and there is nothing to decide.
