### ISSUE TITLE
Config.yml.sample is invalid

### ISSUE THREAD

**Issue by roschaefer** [tino-junge/cinema-app#40]
Current config.yml.sample has no sequels here:
```
  v2: &v2_config
    file: 'iamerror_02.mp4'
    question: 'What should Hanna do?'
    answers:
      a: 'Stand up'
      b: 'Give up'
```
